package io.github.starlight.kojni

class JniFile(fqcontainer: String, functions: Set<JniFunction>) {
  private val n_functions =
      if (functions.isEmpty()) ""
      else functions.joinToString(separator = "", transform = JniFunction::buildFunction)

  private val impl_functions by lazy {
    functions.joinToString(separator = System.lineSeparator(), transform = JniFunction::impl)
  }
  private val filename = fqcontainer.replace('.', '/')
  private val u_fqcontainer = fqcontainer.replace('.', '_')

  private fun buildFile(): String =
      """
      /* DO NOT EDIT THIS FILE - it is machine generated */
      #include <jni.h>
      /* Header for class ${u_fqcontainer} */

      #ifndef _Included_${u_fqcontainer}
      #define _Included_${u_fqcontainer}
      #ifdef __cplusplus
      extern "C" {
      #endif
      ${n_functions}
      #ifdef __cplusplus
      }
      #endif
      #endif
  """.trimIndent()

  operator fun component1() = filename
  operator fun component2() = buildFile()

  fun impl() =
      """
    #include <jni.h>

    #include "${filename}${".h"}"

    using namespace std;

    extern "C" {
    ${impl_functions}
    } // extern

  """.trimIndent()
}
