package io.github.starlight.kojni

class JniFile(val u_fqcontainer: String, functions: Set<JniFunction>) {
  val n_functions by lazy {
    val builder by lazy { StringBuilder() }
    functions.forEach { builder.append(it.buildFunction()) }
    return@lazy builder.toString()
  }

  fun buildFile(): String {
    return """
        /* DO NOT EDIT THIS FILE - it is machine generated */
        #include <jni.h>
        /* Header for class ${u_fqcontainer} */

        #ifndef _Included_${u_fqcontainer}
        #define _Included_${u_fqcontainer}
        #ifdef __cplusplus
        extern "C" {
        #endif
        ${n_functions}
        #ifdef __cplusplus
        }
        #endif
        #endif
    """.trimIndent()
  }
}
